# Generated by Django 4.0.3 on 2022-05-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_comment_parent_remove_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='timestamp',
        ),
    ]
